### PR TITLE
rework f3 series rcc take 2

### PR DESCRIPTION
**Pull request by dreilly1982**
Reworked so f3 series (except STM32F37xx) will now not have ADC periphs RCC mapped, will handle that in the hal code.  Also added registers for STM32F37xx ADC and RCC.  Still must do SDADC.

### CODE REVIEW

**Comment by dreilly1982** [comment]
The DBGMCUEN register is only documented on the F37 chip, and is included in the rcc_v3_v2.yaml If this is present in all chips but undocumented, I can easily put it back in.

**Comment by dreilly1982** [comment]
ok, added the DBGMCU registers back in

**Comment by dreilly1982** [comment]
found bug, marking as draft

**Comment by dreilly1982** [comment]
Found the bug, and fixed it.

**Review by Dirbaio — APPROVED** [review]
oooh, this is great. It gets *so many* new ADC RCC bits. Thanks for working on this!

**Pull request merged**
