### PR TITLE
Kkoppul2/u5 comp support

### PR DESCRIPTION
**Pull request by kkoppul2**
Add U5 comparator support
Clean up U0 comparator yaml

### CODE REVIEW

**Comment by Dirbaio** [comment]
why remove the winout, winmode, polarity enums? they're 1-bit, but they're not "useless" because they convery meaning. For example "polarity: NotInverted, Inverted" makes sense, "polarity: true/false" doesn't. it'd make sense if the field was named "invert: true/false" but it isn't.

**Comment by kkoppul2** [comment]
That's fair, I'll update that.

**Comment by kkoppul2** [comment]
@Dirbaio Fixed it

**Review by Dirbaio — APPROVED** [review]
thanks!

**Pull request merged**
