### PR TITLE
Add support for HSEM

### PR DESCRIPTION
**Pull request by taunusflieger**
Add support for the hardware semaphore 

The main issue with implementing HSEM is that the Cube XML is missing HSEM information except for the wle5. Without the Cube XML information the data generation process will not generate the data for HSEM. Therefore a preliminary patch has been implemented in chips.rs (see also https://github.com/embassy-rs/stm32-data/issues/444). I'm unsure about the implemented patch - would appriciate feedback.

chips with HSEM 
h745
h747
h755
h757
h735
h7b3
h753v
h753
h743
h743v
mp157
mp153
wb55
wba52
wl5x_cm0p
wl5x_cm4
wle5 

The current draft PR contains the HSEM implementation for: 

h745
h747
h755
h757
wle5

### CODE REVIEW

**Comment by taunusflieger** [comment]
Hey @Dirbaio would appreciate your input here

**Comment by Dirbaio** [comment]
We already have [GHOST_PERIS](https://github.com/embassy-rs/stm32-data/blob/2b7ec569a5510c324693f0515ac8ea20b12917a9/stm32-data-gen/src/chips.rs#L1006) for handling peripherals that are missing in cubedb, can you add HSEM there instead of adding custom code?

Also, there's no way there's 8 versions. from looking at the RMs, there's:
  - h7 singlecore: 32 semaphores, 1 irq line.
  - h7 multicore: 32 semaphores, 2 irq lines (one per core)
  - wb: 32 semaphores, 2 irq lines (one per core)
  - wba: 16 semaphores, trustzone shit (LOCK, PRIV bits, secure and nonsecure irq lines)
  - wl5: 16 semaphores, 2 irq lines (one per core)
  - wle: 16 semaphores, 1 irq line

H7 multicore and WB are the same, so this is 5 versions in total.

Can you rearrange versions to match that? also, please make sure to cleanup the yamls (convert stuff to arrays, remove dupe enums, remove useless single-bot enums...), and minimize the diff between versions for easy review.

**Comment by taunusflieger** [comment]
The following list shows the different hsem yaml versions and the corresponding chips.
wba is on purpose not included at is complex and very different from the others which will also make the HSEM implementation in the HAL more complex. I leave this out for another PR.

**v1:**
- h747
- wb55

**v2:**
- h735
- h7b3
- h753v
- h753
- h743
- h743v

**v3:**
- wl5x_cm0p
- wl5x_cm4

**v4:**
- wle5

**Comment by Dirbaio** [comment]
- in v1,v2 coreid is 4 bits, not 8bits. in CR, R, RLR.
- To make it easier to make the HAL to work on all chips, you might want to unify the registers more. Up to you, though. Here are some ideas:
  - rename "MASTERID" to "COREID"
  - Always make the interrupt registers an array, just make it length 1 or 2 depending on the chip.

**Review by Dirbaio — APPROVED** [review]
thanks!

**Pull request merged**
