### PR TITLE
Include base addresses for flash and ram.

### PR DESCRIPTION
**Pull request by bobmcwhirter**
Remove 'null' entries for datasheets/reference-manuals.

### CODE REVIEW

**Comment by Dirbaio** [comment]
Very interesting! I wonder if we should have separate fields for every "kind" of RAM?

**Comment by bobmcwhirter** [comment]
Yah, I was starting to think about that.

**Comment by Dirbaio** [comment]
Also maybe it's more natural to store the size in bytes, not in kbs. The ST XMLs store it in KBs but I find that quite strange, you can't represent smalle memory regions, like 512-byte for example

**Comment by bobmcwhirter** [comment]
I'll keep poking on it and refining this PR.

**Comment by Dirbaio** [comment]
Having size of each region is super nice, thanks! :) 

There's a few that don't make sense though. For example, on stm32f031c4 the total is less thank bank1. It seems the correct one is 16384.

```yaml
flash:
ram: 4
  bytes: 16384
  regions:
    BANK_1:
      base: 0x8000000
      bytes: 32768
```

**Comment by bobmcwhirter** [comment]
I’ll investigate. The XMLs have a few configurations and xmltodict pruned
off those sub trees so it was sorta a challenge.

I’ll figure it out.

**Pull request merged**
