### PR TITLE
Add LPUART peripherals

### PR DESCRIPTION
**Pull request by mro95**
As I mentioned in issue #120, I would like to begin adding support for LPUART.
I followed the instructions of @Dirbaio

Let me know what you think

### CODE REVIEW

**Comment by mro95** [comment]
I noticed that there is no DMA block, did i forget something to do?

**Comment by Dirbaio** [comment]
Thanks for the PR!

There's actually 4 different versions of LPUART according to the SVDs (I've done the diffing, added them to the [table](https://docs.google.com/spreadsheets/d/1-R-AjYrMLL2_623G-AFN2A9THMf8FFMpFD4Kq-owPmI/edit#gid=1972450814))

- v1: L0, L4, L4+
- v2: G0, G4, L5, WL -- all regs from v1, plus PRESC
- v3: H7, WB -- all regs from v1, plus PRESC, GTPR, RTOR
- v4: U5 -- all regs from v1, plus PRESC, AUTOCR (yes, removes GTPR, RTOR :shrug: )

You've mapped all chips to version v1, which s not right. You should either add all versions, or If you personally only care about L4 support, add v1 only to L0, L4, L4+ ) and I'll add the others. Up to you :) 

(The reason I'd rather not have "wrong" versions is that later on it's much easier to catch "there's no LPUART for U5" than "there's LPUART for U5 but it's missing registers")

**Comment by Dirbaio** [comment]
> I noticed that there is no DMA block, did i forget something to do?

I think it's because ST calls the DMA request `LPUART` while the peripheral is `LPUART1`, so the script doesn't match them: https://github.com/embassy-rs/stm32-data-sources/blob/main/cubedb/mcu/IP/DMA-STM32L4A6_dma_v1_1_Modes.xml#L720

An `if` in the right place in the script should solve it...

(ST loves to name the peripheral FOO instead of FOO1 when there's just one, and worst of all is they make the renames inconsistenly! :angry: . I hope to someday make the scripts normalize FOO to FOO1 so that naming is consistent between chips that have 1 foo and many foos, but that's a battle for another day...)

**Comment by Dirbaio** [comment]
Thanks for working on this!

Turns out GTPR, RTOR existing is a mistake in the SVDs, so v2 and v3 are really the same... I've merged them.

I've fixed up v1 and v2 so the diff between them is as small as possible, and removed useless "0=disabled 1=enabled"  enums.

**Comment by Dirbaio** [comment]
For some reason I can't push to this branch, I've manually merged this + my fixups to main.

**Pull request closed without merging**
