### PR TITLE
Add EXTI and IPCC for STM32WB55

### PR DESCRIPTION
**Pull request by Tiwalun**
Add EXTI  for STM32WB55, IPCC for STM32WB55 and similar.

### CODE REVIEW

**Comment by Dirbaio** [comment]
Could you arrayify all the possible registers? on IPCC the registers for core1 and core2 seem to be equal. On EXTI it seems everything can be arrayified too. 

In general we try to arrayify everything that can be, so that writing HALs is then much easier. When arrayifying it's OK to "uniformize" things a bit. For example EXTI RTSR1, RTSR2 have different bits implemented, but it's OK to make them just have all 32bits implemented, as if all 64 bits were implemented. This allows writing stuff like this in HALs: `exti.RTSR(n/32).write(|w| w.set_rt(n%32, true));` which is much nicer than big macros/matches.

**Comment by Tiwalun** [comment]
Is it possible to create 2-dimensional arrays? 

For `EXTI`, I want to create an array out of `C1EMR1` and `C1EMR2`, but these could then be combined with `C2EMR1` and `C2EMR2` as well.

**Comment by Dirbaio** [comment]
Not 2-dimensional, but you can create a "core" block that has one core's EMR, RTSR, FTSR, etc as arrays of len 2, then make an array of len 2 of that.

**Review by Dirbaio — APPROVED** [review]
Very nice! Thanks!

**Pull request merged**
