### PR TITLE
Fix dac on g4

### LINKED ISSUE #298: Dac in stm32g431c8
The dac definitions are missing from this chip. It seems like it already has an entry in the perimap though. 

It also has the data for it in the json.
https://github.com/embassy-rs/stm32-data-generated/blob/4f60a9c3c9583915a33c842a35574bead53aa8da/data/chips/STM32G431C8.json#L670

What would I need to change?

### PR DESCRIPTION
**Pull request by jrmoulton**
Fixes #298 

This fixes the matching for dac on stm32g4

### CODE REVIEW

**Comment by Dirbaio** [comment]
G4 is a newer DAC version, it adds the STR1, STR2, STMODR registers. Can you make it `dac_v4.yaml`?

**Comment by jrmoulton** [comment]
I followed the readme for generating a new yaml. For all yaml files that were created, I ran a diff and they all matched exactly so I placed it as dac_4v.yaml.

**Comment by jrmoulton** [comment]
g4 was also the only chip that generated yaml files for dac_v4

```
 ./d extract-all DAC4

processing c011 ...No Peripheral
processing c031 ...No Peripheral
processing f0x0 ...No Peripheral
processing f0x1 ...No Peripheral
processing f0x2 ...No Peripheral
processing f0x8 ...No Peripheral
processing f100 ...No Peripheral
processing f101 ...No Peripheral
processing f102 ...No Peripheral
processing f103 ...No Peripheral
processing f107 ...No Peripheral
processing f215 ...No Peripheral
processing f217 ...No Peripheral
processing f301 ...No Peripheral
processing f302 ...No Peripheral
processing f303 ...No Peripheral
processing f373 ...No Peripheral
processing f3x4 ...No Peripheral
processing f401 ...No Peripheral
processing f405 ...No Peripheral
processing f407 ...No Peripheral
processing f410 ...No Peripheral
processing f411 ...No Peripheral
processing f412 ...No Peripheral
processing f413 ...No Peripheral
processing f427 ...No Peripheral
processing f429 ...No Peripheral
processing f446 ...No Peripheral
processing f469 ...No Peripheral
processing f730 ...No Peripheral
processing f745 ...No Peripheral
processing f750 ...No Peripheral
processing f765 ...No Peripheral
processing f7x2 ...No Peripheral
processing f7x3 ...No Peripheral
processing f7x6 ...No Peripheral
processing f7x7 ...No Peripheral
processing f7x9 ...No Peripheral
processing g030 ...No Peripheral
processing g031 ...No Peripheral
processing g041 ...No Peripheral
processing g050 ...No Peripheral
processing g051 ...No Peripheral
processing g061 ...No Peripheral
processing g070 ...No Peripheral
processing g071 ...No Peripheral
processing g081 ...No Peripheral
processing g0b0 ...No Peripheral
processing g0b1 ...No Peripheral
processing g0c1 ...No Peripheral
processing g431 ...OK
processing g441 ...OK
processing g471 ...OK
processing g473 ...OK
processing g474 ...OK
processing g483 ...OK
processing g484 ...OK
processing g491 ...OK
processing g4a1 ...OK
processing h503 ...No Peripheral
processing h562 ...OTHER FAILURE
processing h563 ...OTHER FAILURE
processing h573 ...No Peripheral
processing h735 ...No Peripheral
processing h743 ...No Peripheral
processing h743v ...No Peripheral
processing h747cm4 ...No Peripheral
processing h747cm7 ...No Peripheral
processing h753 ...No Peripheral
processing h753v ...No Peripheral
processing h7b3 ...No Peripheral
processing l0x0 ...No Peripheral
processing l0x1 ...No Peripheral
processing l0x2 ...No Peripheral
processing l0x3 ...No Peripheral
processing l100 ...No Peripheral
processing l151 ...No Peripheral
processing l162 ...No Peripheral
processing l412 ...No Peripheral
processing l4r5 ...No Peripheral
processing l4r9 ...No Peripheral
processing l4x1 ...No Peripheral
processing l4x2 ...No Peripheral
processing l4x3 ...No Peripheral
processing l4x5 ...No Peripheral
processing l4x6 ...No Peripheral
processing l552 ...No Peripheral
processing l562 ...No Peripheral
processing mp153 ...No Peripheral
processing mp157 ...No Peripheral
processing u535 ...No Peripheral
processing u545 ...No Peripheral
processing u575 ...OTHER FAILURE
processing u585 ...OTHER FAILURE
processing u595 ...No Peripheral
processing u599 ...No Peripheral
processing u5a5 ...No Peripheral
processing u5a9 ...No Peripheral
processing u5xx ...No Peripheral
processing wb55 ...No Peripheral
processing wba52 ...OTHER FAILURE
processing wl5x_cm0p ...No Peripheral
processing wl5x_cm4 ...No Peripheral
processing wle5 ...No Peripheral
```

**Comment by jrmoulton** [comment]
> G4 is a newer DAC version, it adds the STR1, STR2, STMODR registers. Can you make it `dac_v4.yaml`?

I don't see strmodr in the yaml

**Comment by jrmoulton** [comment]
Also the dac is missing the `set` method. Any idea why that wouldn't be there?

**Comment by jrmoulton** [comment]
The project actually doesn't currently build.

```
 ...00 as usize as _) } ; pub const DAC1 : dac :: Dac = unsafe { dac :: Dac :: from_ptr (0x5000_0800 as usize as _) } ; pub const DAC3 : dac :: Dac = unsafe { dac :: Dac :: from_ptr (0x5000_100...
   |                                                                        ^^^
   |                                                                        |
   |                                                                        could not find `Dac` in `dac`
   |                                                                        help: a struct with a similar name exists: `Dac1`

```

I'm trying to track down what is going wrong when generating the pac but I definitely don' understand the generating code perfectly and any pointers would be appreciated.

**Comment by Dirbaio** [comment]
> g4 was also the only chip that generated yaml files for dac_v4
> 
>     ./d extract-all DAC4

the argument to `extract-all` is the peripheral name. Most chips don't have up to 4 DACs. You can try DAC1 to get more chips.

> I don't see strmodr in the yaml

it's STMODR, and it *is* there :) 

> the project actually doesn't currently build.

you need to name the register block "DAC". `block/DAC:` instead of `block/DAC1:`

---

reviewing the `dac_v4.yaml` you've added: could you fix it up so the diff to `dac_v3.yaml` is minimal? For example, see the diff:

screenshot-2023-10-31_23-55-30

There's `DAC_` prefixes that can be removed, the registers should be grouped into arrays etc. Could yo check that? Reducing the diff is essential, so it's later possible to write a single HAL driver that works across multiple versions of DAC.

Since v4 is the same as v3 with a few additions, it's probably easier to take the v3 yaml and manually add the new things, rather than taking the v4 yaml from SVD and fixing it from scratch.

Could you also ensure STR1/STR2 are a register array, since the two registers are identical? Same for the fields in STMODR.

**Comment by jrmoulton** [comment]
Ahh I see. Thanks for clarifying. I'll do that

**Comment by adamgreig** [comment]
I accidentally opened #306 without seeing that this existed; I've done all the tidying up (remove prefixes, arrayify, etc) such that the only diff from v3 is the new fields and the TSEL enum. Didn't mean to step on toes, sorry!

**Comment by jrmoulton** [comment]
No problem! I'll just be happy to have it working. I can close this now or wait till #306 is merged

**Comment by jrmoulton** [comment]
closing in favor of #306

**Pull request closed without merging**
