### PR TITLE
Remove invalid bits from F4, L4 RCC

### PR DESCRIPTION
**Pull request by timokroeger**
Required for https://github.com/embassy-rs/embassy/pull/331

### CODE REVIEW

**Comment by Dirbaio** [comment]
I'm not sure this is right, the F410 does have RNGEN in AHB1ENR bit 31. The reason why they're both in the yaml is because it was probably made with `merge_regs.py`.

We probably have to split the rcc_f4 into many...

From the SVDs:

```
F410: AHB1ENR.RNGEN, bit 31
F411: no RNG
F412: AHB2ENR.RNGEN, bit 6
F413: AHB2ENR.RNGEN, bit 6
F427: AHB2ENR.RNGEN, bit 6
F429: AHB2ENR.RNGEN, bit 6
F446: no RNG
F469: AHB2ENR.RNGEN, bit 6

**Comment by timokroeger** [comment]
The L4 bit indeed is known limitation from the SVD file:
https://github.com/stm32-rs/stm32-rs/blob/master/devices/stm32l4x1.yaml#L6-L10

Not sure why it’s not correctly patched… either I’m still doing something wrong or there is a bug in the stm32-rs scripts.

**Comment by Dirbaio** [comment]
Oh I see! then the L4 change is correct, but the F4 still needs splitting

**Comment by Dirbaio** [comment]
Awesome! :+1:

**Pull request merged**
